<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>DanClientSetup</AssemblyName>
    <RootNamespace>Installer.UI</RootNamespace>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <TargetPlatformIdentifier>windows</TargetPlatformIdentifier>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Assets\danclient.ico</ApplicationIcon>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="payload.zip" Condition="Exists('payload.zip')" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.HarfBuzz" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Win32" Version="$(AvaloniaVersion)" />
  </ItemGroup>
</Project>
